### ISSUE TITLE
Site Wide Styles

### ISSUE THREAD

**Issue by atxfjrotc** [atxfjrotc/USwap#11]
Need to determine appropriate colors, themes, design language for the site. @erobx

**Comment by erobx** [comment]
Should we go for a Gator themed site?

**Comment by atxfjrotc** [comment]
Go on the gator theme, not yet on the light/dark mode?

**Comment by erobx** [comment]
Well we should incorporate a dark/light theme under the umbrella of a gator theme no?

**Comment by atxfjrotc** [comment]
We could always design the light mode gator theme first?

**Comment by erobx** [comment]
For right now let's just use the predefined themes that come with their own palettes: https://material.angular.io/guide/theming. Once we have functionality, we should then add our own touch.

**Comment by atxfjrotc** [comment]
100% agree

**Comment by atxfjrotc** [comment]
This is going to be an ongoing consideration, not ready for a specific sprint.

**Comment by atxfjrotc** [comment]
Working. To Do below.

- [ ] Create Orange Light/Dark Themes
- [ ] Create Blue Light/Dark Themes
- [ ] For Dark Mode, Site Background should go close to black.
- [ ] For Light Mode, site background should be white ish.

**Comment by atxfjrotc** [comment]
given limited time, orange theme will suffice. closing.
