### ISSUE TITLE
Integrate Front End and Back End

### ISSUE THREAD

**Issue by atxfjrotc** [atxfjrotc/USwap#23]
If this has already been done, please make a comment to that effect, and close this.

**Comment by Daniel-Moraes1** [comment]
REST API is up. Just need to push inputs from front end side if you could handle that or I can take a look let me know.

**Comment by erobx** [comment]
We can complete the pull request to integrate our current front end features if that's okay.

**Comment by Andrew7044** [comment]
Done since Sprint 3, some additional functionality will be added Sprint 4, but has been done.
