### ISSUE TITLE
Create initial backend storage of users

### ISSUE THREAD

**Issue by Andrew7044** [atxfjrotc/USwap#4]
Back end early range tasker, once preliminary project framework is up, is to get initial storage of users set up.

(edited)

**Comment by atxfjrotc** [comment]
Prospective package is not thread safe. @erobx you think that's an issue?

**Comment by atxfjrotc** [comment]
Though honestly as a v0.x thing, i don't think its a huge deal

**Comment by Daniel-Moraes1** [comment]
We can just use an existing Golang sql package. Don't think we need to implement these data structures ourselves at this point.
https://pkg.go.dev/database/sql

**Comment by atxfjrotc** [comment]
Does that mean that it will set up the database for us? Or is this just a way for us to interface with an existing database? @Daniel-Moraes1

**Comment by Andrew7044** [comment]
Yea I meant to just download a package that will do it for us. If we can implement the same functionality easier using the SQL package let's do that.

**Comment by Andrew7044** [comment]
https://golangbot.com/connect-create-db-mysql/
