### ISSUE TITLE
Need Login API Draft

### ISSUE THREAD

**Issue by atxfjrotc** [atxfjrotc/USwap#5]
@Daniel-Moraes1 per your request,

Need a serviceable HTTP request handler implemented to respond to requests to 'serverurl/login', with JSON data that (suggested variable names) provides the following info: loginSuccess = true/false. Hoping to have this for our meeting tomorrow so that way we can work on bringing the two together.

**Comment by Daniel-Moraes1** [comment]
Done

**Comment by Daniel-Moraes1** [comment]
Closing issue functionality works as expected
