### ISSUE TITLE
Inital Landing Page (Homepage)

### ISSUE THREAD

**Issue by erobx** [atxfjrotc/USwap#8]
Main page where users first enter the site. Should display items up for trade, list of filters, and toolbar.

**Comment by atxfjrotc** [comment]
User Story:

As a **college student**, I want to **trade my toaster for someone's blender**, so that I can **make protein shakes instead of bagels for breakfast**.

**Comment by atxfjrotc** [comment]
Proposed Implementation 1:

1. Land on a traditional e commerce site, UI common and instantly familiar (amazon, walmart, target, they all do the same basic thing).

> a. Display a title bar with a link to site home, an icon to log in/manage the user profile, and a search bar.
> b. Have a list of filters (Sprint 2-3-4 maybe)
> c. Display cards of items available to trade, with name, picture, and item sought in return.

Proposed Implementation 2:

1. Land on a USwap Homepage, with a ChatGPT integrated search field asking "What do you **have** and/or want to **swap for**."
2. Have a UI that will help users narrow down what exactly it is that they **Have** and what it is they want to **Swap For**.
3. Show a more limited version of the first implementation.

**Comment by atxfjrotc** [comment]
The second proposed implementation of the homepage (the navigation through a narrow down ui, etc) remains unfinished. Reopening until then

**Comment by atxfjrotc** [comment]
UI Done per Pull Request 11
