### ISSUE TITLE
User profile

### ISSUE THREAD

**Issue by erobx** [atxfjrotc/USwap#9]
Basic profile page with user credentials, picture, and inventory; will add features based on user stories. Have to allow users to manage their settings.

**Comment by atxfjrotc** [comment]
User Story:

As a **college student**, I want to **manage my profile**, so that I can **be set up to Swap with other students for things I want or need**.

**Comment by atxfjrotc** [comment]
In progress a/o 2/9/23

**Comment by atxfjrotc** [comment]
Finished in PR 11
